name: Release Server
on:
  push:
      branches: ["main"]

  workflow_dispatch:

env:
  url: https://metron.kotlingames.shop
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    permissions: write-all
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
#    runs-on: self-hosted
    steps:
      # only non self-hosted
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: set properties value of server
        run: |
          setProperty(){
            awk -v pat="^$1=" -v value="$1=$2" '{ if ($0 ~ pat) print value; else print $0; }' $3 > $3.tmp
            mv $3.tmp $3
          }
          setProperty "server" "${{ env.url }}" "gradle.properties"
          setProperty "version" "v0.0.${{github.run_number}}" "gradle.properties"
      - run: git tag ${{github.run_number}}

      - name: Prepare Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: |
          ./gradlew :client:jsBrowserProductionWebpack
      - name: server.jar
        run: |
          ./gradlew :server:packageJvmFatJar
          cp -r server/build/libs/server-all.jar server/build/libs/server.jar

      - name: Commit files
        run: |
          URL=$(git remote get-url origin)
          cd ./client/build/dist
          git init
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "changes"
          git branch artifact
          git switch artifact
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin artifact --force

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build apk
        run: ./gradlew :client:installAndroidRelease || true
      - name: rename .apk
        run: cd client/build/outputs/apk/release && mv client-release.apk client.apk

      - uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          repo: ${{ github.repository }}
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build #${{github.run_number}}"
          automatic_release_tag: "${{github.run_number}}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            server/build/libs/server.jar
            client/build/outputs/apk/release/client.apk
          prerelease: false
      - shell: bash
        run: |
          sleep 10
          curl -d "${{ secrets.SHUTDOWN_KEY }}" -X POST ${{ env.url }}/shutdown | true
  buildExe:
    name: Release .exe
    runs-on: windows-latest
    permissions: write-all
    needs: release
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: set properties value of server
        run: |
          echo "import java.io.File;import java.io.FileInputStream;import java.io.FileOutputStream;import java.util.Arrays;import java.util.Iterator;import java.util.Properties;public class Prop {    public static void main(String[] args) throws Exception {        Iterator<String> iterator = Arrays.stream(args).iterator();        if (!iterator.hasNext()) return;        String fileName = iterator.next();        File file = new File(fileName);        Properties props = new Properties();        props.load(new FileInputStream(file));        while (true) {            if (!iterator.hasNext()) break;            String key = iterator.next();            if (!iterator.hasNext()) break;            String value = iterator.next();            props.setProperty(key, value);        }        props.store(new FileOutputStream(file), null);    }}" > Prop.java
          java Prop.java gradle.properties server ${{ env.url }}
          java Prop.java gradle.properties version v0.0.${{github.run_number}}
      - run: git tag ${{github.run_number}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Buid
        run: |
          # brew install wine-stable
          irm get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin 
          scoop install gh
          ./gradlew :client:linkReleaseExecutableMingwX64
          cd client\build\bin\mingwX64
          Rename-Item -Path "releaseExecutable" -NewName "client"
          cd ..
          cd ..
          cd ..
          cd ..
          Compress-Archive -Path .\client\build\bin\mingwX64\client -DestinationPath .\client\build\bin\mingwX64\client.zip
          Get-ChildItem -Path . -File -Recurse
          gh release upload ${{github.run_number}} .\client\build\bin\mingwX64\client.zip --repo ${{ github.repository }}
